apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
commonLabels:
  monokle: kustomize-demo
namespace: default
resources:
  - test-deployment.yaml
  - test-service.yaml
  - test-config.yaml
